project_id = "hybuoksgodflxjhjoufv"

[functions.webhook-produtos]
verify_jwt = false

[functions.webhook-pessoas]
verify_jwt = false

[functions.api-v1-produtos]
verify_jwt = false

[functions.api-v1-pessoas]
verify_jwt = false

[functions.api-v1-pedidos]
verify_jwt = false

[functions.test-smtp]
verify_jwt = true
